### ISSUE TITLE
[Bug]when using in anaconda,find such error:AttributeError: 'Route' object has no attribute 'handler'

### ISSUE THREAD

**Issue by liuyuzhou** [sanic-org/sanic-openapi#222] opened 2021-03-31 05:47 UTC
[ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "E:\tools\anaconda\lib\site-packages\sanic\app.py", line 918, in run
    serve_single(server_settings)
  File "E:\tools\anaconda\lib\site-packages\sanic\server.py", line 725, in serve_single
    serve(**server_settings)
  File "E:\tools\anaconda\lib\site-packages\sanic\server.py", line 562, in serve
    trigger_events(after_start, loop)
  File "E:\tools\anaconda\lib\site-packages\sanic\server.py", line 352, in trigger_events
    result = event(loop)
  File "E:\tools\anaconda\lib\site-packages\sanic_openapi\swagger.py", line 81, in build_spec
    if hasattr(route.handler, "view_class"):
AttributeError: 'Route' object has no attribute 'handler'
Traceback (most recent call last):
  File "F:/workspace/transport_capacity/server_enter.py", line 26, in <module>
    app.run(host=app_ip_addr, port=app_port, debug=True)
  File "E:\tools\anaconda\lib\site-packages\sanic\app.py", line 918, in run
    serve_single(server_settings)
  File "E:\tools\anaconda\lib\site-packages\sanic\server.py", line 725, in serve_single
    serve(**server_settings)
  File "E:\tools\anaconda\lib\site-packages\sanic\server.py", line 562, in serve
    trigger_events(after_start, loop)
  File "E:\tools\anaconda\lib\site-packages\sanic\server.py", line 352, in trigger_events
    result = event(loop)
  File "E:\tools\anaconda\lib\site-packages\sanic_openapi\swagger.py", line 81, in build_spec
    if hasattr(route.handler, "view_class"):
AttributeError: 'Route' object has no attribute 'handler'

**Comment by artcg** [comment] 2021-04-01 16:21
dupe of #221

**Closed by artcg** 2021-04-01 16:21 UTC

**Comment by liuyuzhou** [comment] 2021-04-02 02:13
I use the newest code, the question still.
I checkout the newest code.
If use pip install,the version it the same as before.

**Comment by liuyuzhou** [comment] 2021-04-02 02:14
> dupe of #221

So,is the newest code merge to the master branch.

**Comment by artcg** [comment] 2021-04-02 11:57
No it is not in master branch, try checking out s21 branch of artcg/sanic-openapi

**Comment by liuyuzhou** [comment] 2021-04-05 02:13
it seems I can't see this branch,when will you merge this code to master?
